export const faqs = [
  {
    category: "Greeting",
    question: "Hello",
    answer: "Hello",
  },
  {
    category: "Greeting",
    question: "Hii",
    answer: "Hello",
  },
  {
    category: "About MRSAC",
    question: "What is MRSAC?",
    answer:
      "MRSAC stands for Maharashtra Remote Sensing Application Centre. It is an autonomous organization under the Department of Planning, Government of Maharashtra, specializing in remote sensing, GIS, and geospatial data analysis.",
  },
  {
    category: "About MRSAC",
    question: "Where is MRSAC located?",
    answer: "MRSAC is located in Nagpur, Maharashtra, India.",
  },
  {
    category: "About MRSAC",
    question: "What does MRSAC do?",
    answer:
      "MRSAC develops and provides GIS-based solutions, satellite data analysis, and remote sensing applications for various government departments and research institutions.",
  },
  {
    category: "About MRSAC",
    question: "Who manages the ISMS portal?",
    answer:
      "The ISMS (Internship’s Management System) portal is developed by students as a major project for automating the MRSAC internship process.",
  },

  {
    category: "Internship Process",
    question: "How can I apply for an internship at MRSAC?",
    answer:
      "You can apply directly through the ISMS portal by filling out the registration form, verifying your email, and submitting required documents such as ID proof, LOR, and resume.",
  },
  {
    category: "Internship Process",
    question: "Who can apply for the internship?",
    answer:
      "Only students from colleges within Nagpur pursuing relevant degrees in Computer Science, IT, or related fields can apply.",
  },
  {
    category: "Internship Process",
    question: "What documents are required for registration?",
    answer:
      "You need to upload a valid ID card (Aadhar, PAN, Voter ID, or Driving License), your resume, and a Letter of Recommendation (LOR).",
  },
  {
    category: "Internship Process",
    question: "What is the internship duration?",
    answer:
      "The internship duration options are 1 month, 3 months, or 6 months depending on your academic schedule.",
  },
  {
    category: "Internship Process",
    question: "How will I know if my application is approved?",
    answer:
      "Once approved by the Admin, you’ll receive your login credentials through email.",
  },
  {
    category: "Internship Process",
    question: "Is there an interview process?",
    answer:
      "Yes, after document verification, shortlisted students are invited for an offline interview at MRSAC.",
  },

  {
    category: "ISMS Portal Information",
    question: "What is the ISMS portal?",
    answer:
      "ISMS (Internship’s Management System) is a web-based platform to manage student internships at MRSAC — from registration to document verification, attendance, and completion certificate generation.",
  },
  {
    category: "ISMS Portal Information",
    question: "Who can access the ISMS portal?",
    answer:
      "The portal has three dashboards: Student, Project Manager, and Admin — each with specific roles and permissions.",
  },
  {
    category: "ISMS Portal Information",
    question: "What is the purpose of the verification page?",
    answer:
      "The verification page allows anyone to verify online-generated documents like offer letters, completion letters, and extension letters.",
  },
  {
    category: "ISMS Portal Information",
    question: "How can I reset my password?",
    answer:
      "Use the 'Forgot Password' option on the login page. A password reset link will be sent to your registered email.",
  },
  {
    category: "ISMS Portal Information",
    question: "Can I delete my account?",
    answer:
      "Yes, students can delete their account from the Student Dashboard → Delete Account section.",
  },

  {
    category: "Documents and Certificates",
    question: "How do I upload my documents?",
    answer:
      "Login to the student dashboard → go to the Documents section → upload your ID, resume, and LOR.",
  },
  {
    category: "Documents and Certificates",
    question: "What documents are auto-generated by the system?",
    answer:
      "Offer Letter, Completion Certificate, and Internship Extension Letter are automatically generated after approval.",
  },
  {
    category: "Documents and Certificates",
    question: "Can I verify my offer letter online?",
    answer:
      "Yes, visit the Verification page on the portal and enter the document ID to verify authenticity.",
  },

  {
    category: "Attendance and Progress",
    question: "How do I mark my attendance?",
    answer:
      "Students can mark attendance daily between 11:00 AM and 12:00 PM from the Attendance section in their dashboard.",
  },
  {
    category: "Attendance and Progress",
    question: "Who approves my attendance?",
    answer:
      "Attendance is approved by your Project Manager after your weekly progress report is submitted.",
  },
  {
    category: "Attendance and Progress",
    question: "Can I download my attendance record?",
    answer:
      "Yes, monthly attendance reports can be downloaded from your dashboard.",
  },

  {
    category: "Communication",
    question: "How can I communicate with my project team?",
    answer:
      "Use the Chat section in your dashboard to communicate with your team members and Project Manager.",
  },
  {
    category: "Communication",
    question: "How will I receive important updates?",
    answer:
      "You’ll receive notifications under the Notification tab for alerts like attendance reminders and admin notices.",
  },

  {
    category: "Technical Help",
    question: "I’m not receiving my OTP. What should I do?",
    answer:
      "Please check your spam folder. If the problem persists, contact the ISMS support team at support@mrsac-isms.in.",
  },
  {
    category: "Technical Help",
    question: "My documents are not uploading. What can I check?",
    answer:
      "Ensure the file size is under 5 MB and format is valid (PDF, JPG, PNG). Try refreshing the page or re-logging in.",
  },
  {
    category: "Technical Help",
    question: "The page isn’t loading properly.",
    answer:
      "Please check your internet connection and try using Google Chrome or Microsoft Edge for best performance.",
  },

  {
    category: "Contact and Support",
    question: "How can I contact MRSAC or ISMS support?",
    answer:
      "You can email us at support@mrsac-isms.in or visit the Contact section on the FAQ page.",
  },
  {
    category: "Contact and Support",
    question: "Where can I find the latest internship notifications?",
    answer:
      "All current internship announcements are posted under the Internship section of the ISMS portal.",
  },
];
